export enum Loader {
	BUKKIT = "bukkit",
	BUNGEECORD = "bungeecord",
	CANVAS = "canvas",
	DATAPACK = "datapack",
	FABRIC = "fabric",
	FOLIA = "folia",
	FORGE = "forge",
	IRIS = "iris",
	LITELOADER = "liteloader",
	MINECRAFT = "minecraft",
	MODLOADER = "modloader",
	NEOFORGE = "neoforge",
	OPTIFINE = "optifine",
	PAPER = "paper",
	PURPUR = "purpur",
	QUILT = "quilt",
	RIFT = "rift",
	SPIGOT = "spigot",
	SPONGE = "sponge",
	VANILLA = "vanilla",
	VELOCITY = "velocity",
	WATERFALL = "waterfall",
}
